# Generated by Django 4.1.3 on 2023-02-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user_t',
        ),
    ]
