# Generated by Django 4.1.3 on 2022-12-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MdcMockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_url', models.URLField(verbose_name='请求路径')),
                ('request_headers', models.JSONField(verbose_name='请求头')),
                ('request_params', models.CharField(max_length=1000, verbose_name='请求参数')),
                ('request_body', models.JSONField(verbose_name='请求体')),
                ('response_headers', models.JSONField(verbose_name='响应头')),
                ('response_body', models.JSONField(verbose_name='响应体')),
                ('response_status_code', models.IntegerField(choices=[(1, 200), (2, 403), (3, 500), (4, 503)], verbose_name='状态码')),
                ('response_time', models.IntegerField(max_length=5, verbose_name='响应时间')),
                ('remark', models.TextField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'mdc_mock_tb',
            },
        ),
    ]
