# Generated by Django 4.1.3 on 2022-12-02 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdc_mock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mdcmockmodel',
            old_name='create_time',
            new_name='createTime',
        ),
        migrations.RenameField(
            model_name='mdcmockmodel',
            old_name='request_body',
            new_name='requestBody',
        ),
        migrations.RenameField(
            model_name='mdcmockmodel',
            old_name='request_headers',
            new_name='requestHeaders',
        ),
        migrations.RenameField(
            model_name='mdcmockmodel',
            old_name='request_params',
            new_name='requestParams',
        ),
        migrations.RenameField(
            model_name='mdcmockmodel',
            old_name='request_url',
            new_name='requestUrl',
        ),
        migrations.RenameField(
            model_name='mdcmockmodel',
            old_name='response_body',
            new_name='responseBody',
        ),
        migrations.RenameField(
            model_name='mdcmockmodel',
            old_name='response_headers',
            new_name='responseHeaders',
        ),
        migrations.RenameField(
            model_name='mdcmockmodel',
            old_name='response_status_code',
            new_name='responseStatus_code',
        ),
        migrations.RenameField(
            model_name='mdcmockmodel',
            old_name='response_time',
            new_name='responseTime',
        ),
        migrations.RenameField(
            model_name='mdcmockmodel',
            old_name='update_time',
            new_name='updateTime',
        ),
    ]
