# Generated by Django 4.1.3 on 2022-12-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdc_mock', '0002_rename_create_time_mdcmockmodel_createtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdcmockmodel',
            name='requestParams',
        ),
        migrations.AddField(
            model_name='mdcmockmodel',
            name='mockName',
            field=models.CharField(default='', max_length=100, verbose_name='mock接口名称'),
        ),
        migrations.AddField(
            model_name='mdcmockmodel',
            name='requestParamsKey',
            field=models.CharField(default=None, max_length=100, verbose_name='请求参数'),
        ),
        migrations.AddField(
            model_name='mdcmockmodel',
            name='requestParamsValue',
            field=models.CharField(default=None, max_length=100, verbose_name='请求参数'),
        ),
        migrations.AlterField(
            model_name='mdcmockmodel',
            name='requestBody',
            field=models.JSONField(default=None, verbose_name='请求体'),
        ),
        migrations.AlterField(
            model_name='mdcmockmodel',
            name='responseBody',
            field=models.JSONField(default=None, verbose_name='响应体'),
        ),
        migrations.AlterField(
            model_name='mdcmockmodel',
            name='responseHeaders',
            field=models.JSONField(default=None, verbose_name='响应头'),
        ),
        migrations.AlterField(
            model_name='mdcmockmodel',
            name='responseStatus_code',
            field=models.IntegerField(choices=[(1, 200), (2, 403), (3, 500), (4, 503)], default=1, verbose_name='状态码'),
        ),
        migrations.AlterField(
            model_name='mdcmockmodel',
            name='responseTime',
            field=models.IntegerField(default=4, max_length=5, verbose_name='响应时间'),
        ),
    ]
