# Generated by Django 4.1.3 on 2022-12-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdc_mock', '0003_remove_mdcmockmodel_requestparams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdcmockmodel',
            name='method',
            field=models.IntegerField(choices=[(1, 'GET'), (2, 'POST'), (3, 'PUT')], default=2, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='mdcmockmodel',
            name='requestHeaders',
            field=models.JSONField(default=None, verbose_name='请求头'),
        ),
        migrations.AlterField(
            model_name='mdcmockmodel',
            name='requestUrl',
            field=models.URLField(default=None, verbose_name='请求路径'),
        ),
    ]
