# Generated by Django 4.1.3 on 2022-12-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdc_mock', '0004_mdcmockmodel_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdcmockmodel',
            name='requestUrl',
            field=models.CharField(default=None, max_length=100, verbose_name='请求路径'),
        ),
    ]
